### ISSUE TITLE
rustskins command error

### ISSUE THREAD

**Issue by Owned67** [StefonMiller/CamBot#2]
```
Ignoring exception in command rustskins:
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\ext\commands\core.py", line 204, in wrapped
    ret = await coro(*args, **kwargs)
  File "F:\rust\rf\bot\CamBot-master\cogs\skins_cog.py", line 401, in rustskins
    items, total_item_price = CamBot.get_rust_items('https://store.steampowered.com/itemstore'
  File "F:\rust\rf\bot\CamBot-master\CamBot.py", line 639, in get_rust_items
    item_price_in_double = float(item_price[1:])
ValueError: could not convert string to float: ',10'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 965, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python39\lib\site-packages\discord\ext\commands\core.py", line 886, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python39\lib\site-packages\discord\ext\commands\core.py", line 213, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: could not convert string to float: ',10'
```

**Comment by StefonMiller** [comment]
The command works fine on my machine. I suspect this is because you live in a country that displays price information that is not in USD format. If you want to fix this, you will need to change how data is scraped from the Rust item store.

**Comment by Owned67** [comment]
in .db file or .py file?

**Comment by StefonMiller** [comment]
In the python file. You might have this issue in the future as well, I'm not sure. It's been almost a year since I've worked on this project.

**Comment by Owned67** [comment]
market = Market("USD") replaced  by market = Market("EURO"), im right? if yes, getting same error ^^

**Comment by StefonMiller** [comment]
No. Line 639, it cannot convert the variable item_price to a double because there is a comma in it. You need to change how item_price is retrieved from the div in accordance with your local currency.

**Comment by Owned67** [comment]
can you help me please?

![1rOH4esI4D](https://user-images.githubusercontent.com/1497809/118146629-16811700-b40f-11eb-9b48-7544031a1f8c.png)

**Comment by StefonMiller** [comment]
I am currently at work and can't help you debug this as I don't have an environment set up to run the code. Look at line 638: 

item_price = "".join(i for i in item_price_div.text if 126 > ord(i) > 31)

 This is probably where the problem is

**Comment by Owned67** [comment]
so, ive added:
`               
    item_price = "".join(i for i in item_price_div.text if 126 > ord(i) > 31)
    print(item_price)`

It display correctly the price: 2,10

**Comment by StefonMiller** [comment]
2,10 cannot be converted into a float. It is an issue with the currency format. You will need to convert this currency format to one which can be parsed into a float

**Comment by Owned67** [comment]
`Ignoring exception in command rustskins:
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\ext\commands\core.py", line 204, in wrapped
    ret = await coro(*args, **kwargs)
  File "F:\bot\CamBot-master\cogs\skins_cog.py", line 401, in rustskins
    items, total_item_price = CamBot.get_rust_items('https://store.steampowered.com/itemstore'
  File "F:\bot\CamBot-master\CamBot.py", line 643, in get_rust_items
    predicted_price = '$' + str(skinml.get_predicted_price(item_type))
  File "F:\bot\CamBot-master\skinML\skinml.py", line 75, in get_predicted_price
    pickle_in = open('../data/best_model.pickle', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../data/best_model.pickle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 965, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python39\lib\site-packages\discord\ext\commands\core.py", line 886, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python39\lib\site-packages\discord\ext\commands\core.py", line 213, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: '../data/best_model.pickle'`

**Comment by StefonMiller** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '../data/best_model.pickle'`

You don't have the best_model.pickle file in your data directory. Please try to debug some of these issues yourself before posting here as I won't always have time to respond.

**Comment by Owned67** [comment]
Its your bot or not? archived so please.... no time for debug for you

**Comment by StefonMiller** [comment]
It is my bot yes. It is currently running without issue for me. Any issues you experience are due to your installation/localization. If you can't debug some of the basic issues you've had then I don't think you're going to get it to work.
